// Code generated by goctl. DO NOT EDIT.
package types

type ConvertRequest struct {
	LongUrl string `json:"longUrl" validate:"required"`
}

type ConvertResponse struct {
	ShortUrl string `json:"shortUrl"`
}

type GetLongRequest struct {
	ShortUrl string `path:"shortUrl" validate:"required"`
}

type GetLongResponse struct {
	LongUrl string `json:"longUrl"`
}
